# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xiaoshuo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(307, 278)
        self.btn_ChaXun = QtWidgets.QPushButton(Dialog)
        self.btn_ChaXun.setGeometry(QtCore.QRect(190, 10, 81, 31))
        self.btn_ChaXun.setObjectName("btn_ChaXun")
        self.edit_BookName = QtWidgets.QLineEdit(Dialog)
        self.edit_BookName.setGeometry(QtCore.QRect(20, 20, 151, 20))
        self.edit_BookName.setObjectName("edit_BookName")
        self.list_bookList = QtWidgets.QListView(Dialog)
        self.list_bookList.setGeometry(QtCore.QRect(20, 60, 256, 192))
        self.list_bookList.setObjectName("list_bookList")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_ChaXun.setText(_translate("Dialog", "查询书籍"))
